urls = (
    '/', 'index',
    '/info', 'info',
    '/login', 'login',
    '/logout', 'logout',
    '/settime', 'settime',
    '/getdisk', 'getdisk',
    '/getdiskinfoa', 'getdiskinfoa',
    '/geticoninfo', 'geticoninfo',
    '/getcpuinfo', 'getcpuinfo',
    '/getcpuinfoa', 'getcpuinfoa',
    '/getlog', 'getlog',
    '/deletelog', 'deletelog',
    '/playmusic', 'playmusic',
    '/readbook', 'readbook',
    '/getmovie', 'getmovie',
    '/getuser', 'getuser',
    '/adduser', 'adduser',
    '/deleteuser', 'deleteuser'
)